version: '3.8'

services:
  backend:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    container_name: event_reminder_api
    network_mode: host
    volumes:
      - ./api-service:/app
    env_file:
      - ./api-service/.env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./ui-service
      dockerfile: Dockerfile
    container_name: event_reminder_ui
    network_mode: host
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    volumes:
      - ./ui-service:/app

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: event_db
#    volumes:
#      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db_data:
